name: qiscus_multichannel_widget
description: Omnichannel Platform to Increase Sales and Customer Loyalty.
version: 1.1.6
homepage: https://www.qiscus.com/en

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  qiscus_chat_sdk: ^2.0.2
  freezed_annotation: ^2.0.3
  grouped_list: ^5.1.1
  http: ^0.13.4
  flutter_riverpod: ^2.1.3
  date_format: ^2.0.5
  url_launcher: ^6.1.6
  json_annotation: ^4.5.0
  flutter_secure_storage: ^7.0.1
  cached_network_image: ^3.2.1
  open_filex: ^4.1.1
  file_picker: ^5.2.3
  collection: ^1.16.0
  riverpod: ^2.1.3
  async: ^2.10.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3
  json_serializable: ^6.1.6
  build_runner: ^2.1.7

# dependency_overrides:
#   qiscus_chat_sdk:
#     path: ../qiscus-chat-sdk-flutter

flutter:
  assets:
    - lib/src/assets/
